version: '3'

services:
  app_dev:
    build:
      context: ./
      dockerfile: DockerfileDev
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - env:/app/env
      - data:/app/data
      - node_modules:/app/frontend/node_modules

volumes:
  env:
  data:
  node_modules:
